; LIFT IR -> LLVM IR export
; Generated by LIFT compiler framework
; Target: GPU runtime (cuBLAS/cuDNN backend)

; === Runtime function declarations ===
declare ptr @lift_rt_matmul(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_add(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_sub(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_mul(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_div(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_relu(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_gelu(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_silu(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_softmax(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_sigmoid(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_tanh(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_layernorm(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_rmsnorm(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_batchnorm(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_conv2d(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_conv1d(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_maxpool2d(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_avgpool2d(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_global_avgpool(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_attention(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_multi_head_attention(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_grouped_query_attention(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_flash_attention(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_cross_attention(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_sliding_window_attention(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_paged_attention(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_embedding(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_linear(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_reshape(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_transpose(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_concat(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_moe_dispatch(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_moe_combine(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_fused_matmul_bias_relu(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_fused_matmul_bias(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_fused_linear_gelu(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_fused_linear_silu(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_quantize(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_dequantize(ptr, ptr, ptr, i64, i64)
declare ptr @lift_rt_generic_op(ptr, ptr, ptr, i64, i64)

; === Module: phi3_mini ===

define ptr @embedding(ptr %arg0, ptr %arg1) {
entry:
  ; tensor.embedding (2 inputs -> 1 outputs)
  %r0 = call ptr @lift_rt_embedding(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; core.return (1 inputs -> 0 outputs)
  %r1 = call ptr @lift_rt_generic_op(ptr %arg0, ptr null, ptr null, i64 1, i64 0)
  ret ptr %r1
}

define ptr @layer(ptr %arg0, ptr %arg1, ptr %arg2, ptr %arg3, ptr %arg4, ptr %arg5, ptr %arg6, ptr %arg7, ptr %arg8, ptr %arg9) {
entry:
  ; tensor.rmsnorm (2 inputs -> 1 outputs)
  %r0 = call ptr @lift_rt_rmsnorm(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r1 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r2 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r3 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.grouped_query_attention (3 inputs -> 1 outputs)
  %r4 = call ptr @lift_rt_grouped_query_attention(ptr %arg0, ptr %arg1, ptr null, i64 3, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r5 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.add (2 inputs -> 1 outputs)
  %r6 = call ptr @lift_rt_add(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.rmsnorm (2 inputs -> 1 outputs)
  %r7 = call ptr @lift_rt_rmsnorm(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r8 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.silu (1 inputs -> 1 outputs)
  %r9 = call ptr @lift_rt_silu(ptr %arg0, ptr null, ptr null, i64 1, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r10 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.mul (2 inputs -> 1 outputs)
  %r11 = call ptr @lift_rt_mul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r12 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.add (2 inputs -> 1 outputs)
  %r13 = call ptr @lift_rt_add(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; core.return (1 inputs -> 0 outputs)
  %r14 = call ptr @lift_rt_generic_op(ptr %arg0, ptr null, ptr null, i64 1, i64 0)
  ret ptr %r14
}

define ptr @lm_head(ptr %arg0, ptr %arg1, ptr %arg2) {
entry:
  ; tensor.rmsnorm (2 inputs -> 1 outputs)
  %r0 = call ptr @lift_rt_rmsnorm(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; tensor.matmul (2 inputs -> 1 outputs)
  %r1 = call ptr @lift_rt_matmul(ptr %arg0, ptr %arg1, ptr null, i64 2, i64 1)
  ; core.return (1 inputs -> 0 outputs)
  %r2 = call ptr @lift_rt_generic_op(ptr %arg0, ptr null, ptr null, i64 1, i64 0)
  ret ptr %r2
}

