use lift_core::context::Context;
use thiserror::Error;
use std::fmt::Write;

#[derive(Debug, Error)]
pub enum LlvmExportError {
    #[error("Unsupported operation for LLVM export: {0}")]
    UnsupportedOp(String),
    #[error("Export error: {0}")]
    General(String),
}

#[derive(Debug)]
pub struct LlvmExporter;

impl LlvmExporter {
    pub fn new() -> Self { Self }

    pub fn export(&self, ctx: &Context) -> Result<String, LlvmExportError> {
        let mut output = String::new();

        writeln!(output, "; LIFT IR -> LLVM IR export").unwrap();
        writeln!(output, "; Generated by LIFT framework").unwrap();
        writeln!(output).unwrap();

        for module in &ctx.modules {
            let name = ctx.strings.resolve(module.name);
            writeln!(output, "; Module: {}", name).unwrap();

            for func in &module.functions {
                let fname = ctx.strings.resolve(func.name);
                write!(output, "define void @{}(", fname).unwrap();

                for (i, _param) in func.params.iter().enumerate() {
                    if i > 0 { write!(output, ", ").unwrap(); }
                    write!(output, "ptr %arg{}", i).unwrap();
                }

                writeln!(output, ") {{").unwrap();
                writeln!(output, "entry:").unwrap();

                if let Some(region_key) = func.body {
                    if let Some(region) = ctx.get_region(region_key) {
                        for &block_key in &region.blocks {
                            if let Some(block) = ctx.get_block(block_key) {
                                for &op_key in &block.ops {
                                    if let Some(op) = ctx.get_op(op_key) {
                                        let op_name = ctx.strings.resolve(op.name);
                                        writeln!(output, "  ; {}", op_name).unwrap();
                                    }
                                }
                            }
                        }
                    }
                }

                writeln!(output, "  ret void").unwrap();
                writeln!(output, "}}").unwrap();
                writeln!(output).unwrap();
            }
        }

        Ok(output)
    }
}

impl Default for LlvmExporter {
    fn default() -> Self { Self::new() }
}
